### Creating a Service Account to use for api calls
# We need to create a service account to call the api with valid credentials as a service account
# should be used only once to setup the environment
POST {{endpoint}}/account/service-accounts
Content-Type: application/json
Authorization: Bearer {{personal_access_token}}

{
  "name": "QlikConnectorServiceAccount",
  "permissions": [
     "TMC_USER_MANAGEMENT",
     "TMC_ROLE_MANAGEMENT",
     "AUDIT_LOGS_VIEW",
     "TMC_ENGINE_USE"
  ]
}