@taskId="abc"
@executionId="abc"
@taskName="SimpleHelloWorld"
@tmcEnvironment="PreSales_Testing"
@talendVersion="123"

### Authenticate at TMC
# talend-version is optional
# secret has to be base64 encoded - secret is a combination of service-account-id:service-account-secret
#
# Usecase:
#   - Authorization als Service Account
#
# documentation: https://talend.qlik.dev/apis/oauth/2021-03/
#
# returns
# @name Bearer
POST {{endpoint}}/security/oauth/token
Authorization: Basic lennart.prochnow@cimt-ag.de:{{personal_access_token}}
Content-Type: application/json
Accept: application/json

{
    "grand_type": "client_credentials",
    "audience": "{{endpoint}}"
}

### GET available Tasks
# Search for available tasks executions
# TODO: define body
#
# Returns:
#   - [TaskExtract] (hat keine Task ID - oder vielleicht ist das executable die Task-ID)
#
# Usecase:
#   - Suche nach verfügbaren Tasks mit Suchkriterien/ Filterparameter
#   - Auflisten ALLER möglichen Task
#
# documentation: https://talend.qlik.dev/apis/orchestration/2021-03/#operation_get-available-tasks
GET {{endpoint}}/orchestration/executables/tasks
Authorization: Bearer {{Bearer.access_token}}
Content-Type: application/json

### Search Tasks
# Search for tasks
# Returns:
#   - TaskExtract -> gleiches Ergebnis von oben
#
# TODO: Body not fully covered
#
# Usecase:
#   - Search for executable Tasks
#   - can be visualized for the user
#
# documentation: https://talend.qlik.dev/apis/orchestration/2021-03/#operation_search-tasks
POST {{endpoint}}/orchestration/executables/tasks/search
Authorziation: Bearer {{personal_access_token}}

{
    "name": {{taskName}},
    "environmentId": {{tmcEnvironment}}
}


### GET Task Execution
# Get Task Executions for a specific Task
#
# Returns:
#   - [TaskExecutionStatus]
#       - taskId
#       - status
#       - executionStatus
#       - executionId
#       - errorMessage
#
# Usecase:
#   - Suche nach der Execution eines Tasks unter verwendung von Filterparameter
#   - Lesen des Status eines spezifischen Tasks, die mögliche Fehlermeldung der Taskausführung und noch einiger weiterer Metainformationen über die Taskausführung
#   - Monitoring a specific Task without downloading logs
#   - Troubleshooting a handing task run
#
# Documentation: https://talend.qlik.dev/apis/processing/2021-03/#operation_get-task-executions
GET {{endpoint}}/processing/executables/tasks/{taskId}/executions
Authorization: Bearer {{Bearer.access_token}}
Content-Type: application/json

### Get Task by ID
# Get Task by id
#
# Returns:
#   - TaskV21 (enthält Informationen über die Task)
#       - Name, ID, description, workspaces, version, artifact, tags, parameters
#
# Usecases:
#   - Definition des Tasks anzeigen - was könnte der Nutzer mit diesen Informationen machen?
#
GET {{endpoint}}/orchestration/executables/tasks/{taskId}
Authorization: Bearer {{Bearer.access_token}}
Content-Type: application/json

### Execute Task
# Execute a Task
#
# Returns
#   - Exeuctionidentifier -> executionId
#
# Documentation: https://talend.qlik.dev/apis/processing/2021-03/#operation_execute-task
POST {{endpoint}}/processing/executions
Authorization: Bearer {{Bearer.access_token}}
Content-Type: application/json

{
    "executable": "abc",
    "parameters": {},
    "logLevel": "INFO",
    "timeout": 3600
}

### Get Task execution status
# Get the status and information about a specific task execution
#
# Returns:
#   - JobExecutionStatusV21
#       - executionId, jobId, jobVersion, executionStatus, status
#
# Usecases:
#   - check if the job finished successfully
#
# Documentation: https://talend.qlik.dev/apis/processing/2021-03/#operation_get-task-execution-status
GET {{endpoint}}/processing/executions/{executionId}
Authorization: Bearer {{Bearer.access_token}}
Content-Type: application/json

### Get componente metrics of task runs
# Get the Metrics of the components within a given task run
#   More detailed than just the Task Execution status like in the Get Task Execution Status Endpoint
#
# Returns:
#   - ExecutionComponentMetrics
#       - within the metrics variable sind Metriken für die Komponenten innerhalb eines Tasks
#       - z.B. tFlowMeter, tRowGenerator
#
# Usecase:
#   - Troubleshooting of a failing job
#   - Drill down in error tracking
#
# Documentation: https://talend.qlik.dev/apis/observability-metrics/2021-03/#operation_get-component-metrics-of-task-runs
GET {{endpoint}}/monitoring/observability/executions/{executionId}/component
Authorization: Bearer {{Bearer.access_token}}
Content-Type: application/json

### Terminate Task Execution
# Termine the execution of a task
#
# Usecase:
#   - Ein Fehler ist aufgetreten oder der Prozess verlangt, dass die Execution beendet werden muss
#
# Documentation: https://talend.qlik.dev/apis/processing/2021-03/#operation_terminate-task-execution
DELETE {{endpoint}}/processing/executions/{executionId}
Authorization: Bearer {{Bearer.access_token}}
Content-Type: application/json

### Get Task run-config
GET {{endpoint}}/orchestration/executables/tasks/{taskId}/run-config
Authorization: Bearer {{Bearer.access_token}}
Content-Type: application/json

{
    "trigger": {},
    "runtime": {},
    "parallelExecutionAllowed": false,
    "logLevel": "INFO",
    "remoteRunAsUser": "",
    "timeout": 360,
    "deploymentStrategy": "ROLLING",
    "lineage": false,
    "microservicePort": "8080"
}
